### ISSUE TITLE
In useing componentKit ,do you think It's easy or hard with apple's API

### ISSUE THREAD

**Issue by wy19901227** [itsthejb/CKToolbox#4]

**Comment by itsthejb** [comment]
Are you asking about general thoughts about whether or not to use ComponentKit? Well I would say that's, as with any library choice, heavily dependent on your use case. It's definitely a strong choice for something that closely resembles Facebook Newsfeed, that's for sure! Otherwise, harder to say.

I imagine you decided for yourself in the meantime, though (Mar 25th)?
